name: Deploy Node App to EC2 (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy to EC2
        shell: bash
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          mkdir -p ~/.ssh

          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            set -e
            sudo systemctl start docker || true
            docker stop node-app || true
            docker rm node-app || true
            rm -rf node-app
            git clone "$REPO_URL" node-app
            cd node-app
            docker build -t node-app-image .
            docker run -d --name node-app -p 3000:3000 node-app-image
          EOF
